server:
  port: 8006
spring:
  application:
    name: stat-service
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}