server:
  port: 8005
spring:
  application:
    name: measurement-service
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_URL:mongodb://localhost:27017/measurements}
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}