server:
  port: 9000

spring:
  application:
    name: app-service
  data:
    mongodb:
      auto-index-creation: true
      database: projectX
      host: localhost
      port: 27017
      username: root
      password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka