services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: always
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=simpleClusterName