server:
  port: 8001

spring:
  application:
    name: auth-service
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27117/authDb

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka