server:
  port: 8001
spring:
  application:
    name: auth-service
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27117/authDb
jwt:
  public.key: classpath:public-key.pem
  private.key: classpath:private-key.pem