server:
  port: 8000
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8001
  cloud:
    gateway:
      routes:
        - id: device-service
          uri: lb://device-service
          predicates:
            - Path=/devices/**
        - id: measurement-service
          uri: lb://measurement-service
          predicates:
            - Path=/measurements/**
        - id: stat-service
          uri: lb://stat-service
          predicates:
            - Path=/stats/**
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka