server:
  port: 8000

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8001
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: device-service
          uri: lb://DEVICE-SERVICE
          predicates:
            - Path=/devices/**
        - id: measurements-service
          uri: lb://MEASUREMENT-SERVICE
          predicates:
           - Path=/measurements/**

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka