server:
  port: 8000

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8001
  cloud:
    zookeeper:
      connect-string: localhost:2181