server:
  port: 8001

spring:
  application:
    name: user-service
  data:
    mongodb:
      auto-index-creation: true
      database: projectX
      host: localhost
      port: 27017
      username: root
      password: root

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka