server:
  port: 8005

spring:
  application:
    name: measurement-service
  cassandra:
    keyspace-name: projectx
    local-datacenter: datacenter1
    schema-action: create_if_not_exists

  cloud:
    stream:
      bindings:
        convertToUppercase-in-0:
          destination: measurements-topic
          group: processor
        convertToUppercase-out-0:
          destination: measurements-out-topic

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka