server:
  port: 8005

spring:
  application:
    name: measurement-service
  cassandra:
    schema-action: create_if_not_exists
    keyspace-name: projectx
    local-datacenter: datacenter1
    contact-points: 127.0.0.1
    port: 9042

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka