server:
  port: 8005

spring:
  application:
    name: measurement-service
  cassandra:
    keyspace-name: projectx
    local-datacenter: simpleClusterName
    schema-action: create_if_not_exists
    port: 9042

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka