server:
  port: 8005
spring:
  application:
    name: measurement-service
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27417/measurementDb
  cloud:
    zookeeper:
      connect-string: localhost:2181