server:
  port: 8005

spring:
  application:
    name: measurement-service
  cassandra:
    keyspace-name: projectx
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
  spring:
    kafka:
      bootstrap-servers: todo

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka