server:
  port: 8004

spring:
  application:
    name: device-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8002
  data:
    mongodb:
      auto-index-creation: true
      database: projectX
      host: localhost
      port: 27017
      username: root
      password: root

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka