server:
  port: 8004
spring:
  application:
    name: device-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8001
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27217/deviceDb
  cloud:
    zookeeper:
      connect-string: localhost:2181