server:
  port: 8000

spring:
  application:
    name: AuthServer
  data:
    mongodb:
      auto-index-creation: true
      database: projectX
      host: localhost
      port: 27017
      username: root
      password: root