server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cassandra:
    schema-action: create_if_not_exists
    keyspace-name: projectFmi
    local-datacenter: datacenter1
    contact-points: 127.0.0.1
    port: 9042
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first/**
        - id: second-service
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second/**