server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: firstModule
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first/**