spring:
  application:
    name: second-service

server:
  port: 8002

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka