services:
  serviceRegistry:
    image: zookeeper:3.9.1
    container_name: serviceRegistry
    ports:
      - 2181:2181
  authDb:
    image: mongo:7.0
    container_name: authDb
    ports:
      - 27117:27017
  deviceDb:
    image: mongo:7.0
    container_name: deviceDb
    ports:
      - 27217:27017
  tokenDb:
    image: mongo:7.0
    container_name: tokenDb
    ports:
      - 27317:27017
  measurementDb:
    image: mongo:7.0
    container_name: measurementDb
    ports:
      - 27417:27017