server:
  port: 8004
spring:
  application:
    name: device-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL:http://localhost:9000}
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_URL:mongodb://localhost:27017/devices}
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}