server:
  port: 9000

spring:
  application:
    name: ApiServer
  data:
    mongodb:
      auto-index-creation: true
      database: projectX
      host: localhost
      port: 27017
      username: root
      password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000