server:
  port: 8003
spring:
  application:
    name: token-service
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27317/tokenDb
  cloud:
    zookeeper:
      connect-string: localhost:2181