spring:
  application:
    name: first-service
  cloud:
    discovery:
      enabled: true

server:
  port: 8001

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka