spring:
  application:
    name: first-service
  cassandra:
    schema-action: create_if_not_exists
    keyspace-name: projectFmi
    local-datacenter: datacenter1
    contact-points: 127.0.0.1
    port: 9042

server:
  port: 8001

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka