server:
  port: 8000

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: firstModule
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first/**
        - id: secondModule
          uri: lb://SECOND-SERVICE
          predicates:
            - Path=/second/**