server:
  port: 8003
spring:
  application:
    name: token-service
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_URL:mongodb://localhost:27017/tokens} 
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}