server:
  port: 8003
spring:
  application:
    name: token-service
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/tokens
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka