server:
  port: 8005
spring:
  application:
    name: measurement-service
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/measurements
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka